export const SET_SUBSCRIBED_COURSES = "SET_SUBSCRIBED_COURSES";
export const SET_SUBSCRIBED_INSTRUCTORS = "SET_SUBSCRIBED_INSTRUCTORS";
export const SET_SUBSCRIBED_CATEGORIES = "SET_SUBSCRIBED_CATEGORIES";
